gfx/env/ddk04bk.tga
gfx/env/ddk04dn.tga
gfx/env/ddk04ft.tga
gfx/env/ddk04lf.tga
gfx/env/ddk04rt.tga
gfx/env/ddk04up.tga
models/zm_ded_street3/zm_antenna01.mdl
models/zm_ded_street3/zm_barricade01.mdl
models/zm_ded_street3/zm_barricade02b.mdl
models/zm_ded_street3/zm_bench01.mdl
models/zm_ded_street3/zm_bush01.mdl
models/zm_ded_street3/zm_bush02b.mdl
models/zm_ded_street3/zm_bush03a.mdl
models/zm_ded_street3/zm_bush03c.mdl
models/zm_ded_street3/zm_bush03d.mdl
models/zm_ded_street3/zm_busshelter01.mdl
models/zm_ded_street3/zm_butterfly2.mdl
models/zm_ded_street3/zm_canopy02.mdl
models/zm_ded_street3/zm_car01.mdl
models/zm_ded_street3/zm_car02.mdl
models/zm_ded_street3/zm_car03.mdl
models/zm_ded_street3/zm_car04.mdl
models/zm_ded_street3/zm_couch01.mdl
models/zm_ded_street3/zm_fan01.mdl
models/zm_ded_street3/zm_farmalink.mdl
models/zm_ded_street3/zm_fence02.mdl
models/zm_ded_street3/zm_furniture02.mdl
models/zm_ded_street3/zm_kitchen.mdl
models/zm_ded_street3/zm_lamppost01.mdl
models/zm_ded_street3/zm_lamppost02.mdl
models/zm_ded_street3/zm_paydesk.mdl
models/zm_ded_street3/zm_sign01.mdl
models/zm_ded_street3/zm_sign2.mdl
models/zm_ded_street3/zm_sign3.mdl
models/zm_ded_street3/zm_sink01.mdl
models/zm_ded_street3/zm_sink02.mdl
models/zm_ded_street3/zm_table01.mdl
models/zm_ded_street3/zm_tree01.mdl
models/zm_ded_street3/zm_tree04.mdl
models/zm_ded_street3/zm_umbrella01.mdl
sound/zm_ded_street3/zm_bird1.wav
sound/zm_ded_street3/zm_bird2.wav
sound/zm_ded_street3/zm_bird3.wav
sound/zm_ded_street3/zm_bird4.wav
sound/zm_ded_street3/zm_conditioner.wav
sound/zm_ded_street3/zm_light.wav
sound/zm_ded_street3/zm_loop.wav
sound/zm_ded_street3/zm_pipe.wav
sound/zm_ded_street3/zm_sound1.wav
sound/zm_ded_street3/zm_sound2.wav
sound/zm_ded_street3/zm_street1.wav
sound/zm_ded_street3/zm_street2.wav
sound/zm_ded_street3/zm_truck.wav
sound/zm_ded_street3/zm_water.wav
sprites/zm_ded_street3/grass1.spr
sprites/zm_ded_street3/grass5.spr
sprites/zm_ded_street3/grass6.spr
sprites/zm_ded_street3/grass7.spr
sprites/zm_ded_street3/light.spr