gfx/env/ntdm3_up.tga
gfx/env/ntdm3_dn.tga
gfx/env/ntdm3_lf.tga
gfx/env/ntdm3_rt.tga
gfx/env/ntdm3_ft.tga
gfx/env/ntdm3_bk.tga
models/darkcity/bg_ad01.mdl
models/darkcity/bg_firecar.mdl
models/darkcity/bg_ganpan01.mdl
models/darkcity/bg_pole01.mdl
models/darkcity/bg_pole02.mdl
models/darkcity/bg_pole03.mdl
models/darkcity/bg_sandbags_corner.mdl
models/darkcity/bg_sandbags_fort.mdl
models/darkcity/car_bombed.mdl
models/darkcity/car_mini_silver_wreck.mdl
models/darkcity/car_scrapped.mdl
models/darkcity/car_van02.mdl
models/darkcity/car_vanb01.mdl
models/darkcity/forklift.mdl
models/darkcity/pi_tree2.mdl
models/darkcity/tracker.mdl
models/darkcity/ze_streetlight01.mdl
models/darkcity/ze_tank02.mdl
models/darkcity/ze_vent03.mdl
models/darkcity/zsh_wall_2.mdl
sound/ambience/waterrun.wav
sound/darkcity/burning_metal1.wav
sound/darkcity/silo_wind_loop.wav
sprites/darkcity/flame_burn01.spr
sprites/3dmflagld.spr
