maps/zm_dust_kamp_xmas.txt
models/zm_dust_kamp_xmas/0penguin.mdl
models/zm_dust_kamp_xmas/gign_dead.mdl
models/zm_dust_kamp_xmas/lekstok.mdl
models/zm_dust_kamp_xmas/sneeuwman.mdl
models/zm_dust_kamp_xmas/snowman.mdl
models/zm_dust_kamp_xmas/tree.mdl
models/zm_dust_kamp_xmas/wbaum.mdl
models/zm_dust_kamp_xmas/xt_car2b.mdl
models/zm_dust_kamp_xmas/xt_mr1.mdl
models/zm_dust_kamp_xmas/xt_mr2.mdl
sound/zm_dust_kamp_xmas/s1.wav
sound/zm_dust_kamp_xmas/s2.wav
sound/zm_dust_kamp_xmas/s3.wav
sound/zm_dust_kamp_xmas/s4.wav
sound/zm_dust_kamp_xmas/colind.wav
sound/zm_dust_kamp_xmas/mce.wav
sound/zm_dust_kamp_xmas/stallone.wav
sound/zm_dust_kamp_xmas/waldek.wav
sprites/glow04.spr