zm_tomb.wad
zm_abyss.wad
zm_abyss2.wad
zm_abyss3.wad
grid.wad
dm_union.wad
czcs_downed.wad
cs_camouflage.wad
awp_ruin.wad
maps/zm_rest.res
sprites/glow_tomb.spr
sprites/tdm_smoke.spr
sound/ambience/ghost.wav
sound/ambience/ghost2.wav
sound/ambience/gloomy.wav
sound/ambience/organ.wav
sound/ambience/owl1.wav
sound/ambience/owl2.wav
sound/ambience/wolf.wav
overviews/zm_rest.txt
overviews/zm_rest.bmp
models/basket01.mdl
models/cross01.mdl
models/d_tree01.mdl
models/d_tree02.mdl
models/hay01.mdl
models/hay02.mdl
models/shovel01.mdl
models/shovel02.mdl
models/sulbox01.mdl
models/woodpile.mdl
gfx/env/z3bk.tga
gfx/env/z3dn.tga
gfx/env/z3ft.tga
gfx/env/z3lf.tga
gfx/env/z3rt.tga
gfx/env/z3up.tga