models/as_resident_evil/re_cases.mdl
models/as_resident_evil/re_chair_1.mdl
models/as_resident_evil/re_chair_2.mdl
models/as_resident_evil/re_chair_3.mdl
models/as_resident_evil/re_couch.mdl
models/as_resident_evil/re_cupboard_1.mdl
models/as_resident_evil/re_cupboard_2.mdl
models/as_resident_evil/re_deadguy_1.mdl
models/as_resident_evil/re_deadguy_2.mdl
models/as_resident_evil/re_deadguy_3.mdl
models/as_resident_evil/re_desk.mdl
models/as_resident_evil/re_deskchair_1.mdl
models/as_resident_evil/re_deskchair_2.mdl
models/as_resident_evil/re_filecabinet.mdl
models/as_resident_evil/re_flatscreen.mdl
models/as_resident_evil/re_generator.mdl
models/as_resident_evil/re_laptop.mdl
models/as_resident_evil/re_plant_1.mdl
models/as_resident_evil/re_plant_2.mdl
models/as_resident_evil/re_table.mdl
models/as_resident_evil/re_trashcan.mdl
models/as_resident_evil/re_pipe_stack.mdl
models/props/deskl_ritual.mdl
sound/as_resident_evil/marilyn_manson-resident_evil_main_theme.wav
sound/horror/werewolf1.wav
residentevil.wad
zm_mountains.wad
as_steel.wad
maps/zm_resident_evil_beta2.res

