//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2013 - Infos @ http://www.17buddies.net //
//          More than 85000 maps to download!           //
//////////////////////////////////////////////////////////
// Map Name  : zm_tunnels_final
// Download @: http://www.17buddies.net/17b2/View/Map/88766/zm_tunnels_final.html
// (.res file generated by Sorin Mitac with script version 3.0)
//////////////////////////////////////////////////////////
// Wad files legend:
//     *  : Hardcoded in bsp file, this wad was found (in
//          archive or on 17Buddies's website) but doesn't
//          contains any used texture.
//          However, this file may be necessary.
//     ** : Hardcoded in bsp file, this wad could not be
//          found (neither in archive nor on 17Buddies's
//          website) and thus could not be analysed.
//          However, this file may be necessary.
//////////////////////////////////////////////////////////
gfx/env/tornskyup.tga
gfx/env/tornskydn.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyft.tga
gfx/env/tornskybk.tga
