//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_train_beta3.html
sound/ambience/jetflyby1.wav
sprites/flare1.spr
sound/ambience/flies.wav
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
models/pi_tree1.mdl
sound/ambience/wren1.wav
sound/ambience/boomer.wav
models/v_bloody_zombie_hands.mdl
models/zomhans.mdl
models/re_deadguy_3.mdl
maps/zm_train_beta3.bsp
