//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2013 - Infos @ http://www.17buddies.net //
//          More than 85000 maps to download!           //
//////////////////////////////////////////////////////////
// Map Name  : zm_vendetta_remake_beta4
// Download @: http://www.17buddies.net/17b2/View/Map/88195/zm_vendetta_remake_beta4.html
// (.res file generated by Xopowo with script version 3.0)
//////////////////////////////////////////////////////////
// Wad files legend:
//     *  : Hardcoded in bsp file, this wad was found (in
//          archive or on 17Buddies's website) but doesn't
//          contains any used texture.
//          However, this file may be necessary.
//     ** : Hardcoded in bsp file, this wad could not be
//          found (neither in archive nor on 17Buddies's
//          website) and thus could not be analysed.
//          However, this file may be necessary.
//////////////////////////////////////////////////////////
cs_office.wad
gfx/env/officeup.tga
gfx/env/officedn.tga
gfx/env/officelf.tga
gfx/env/officert.tga
gfx/env/officeft.tga
gfx/env/officebk.tga
// sound/hgrunt/c2a5_hg_lebuz.wav
